### ISSUE TITLE
No render devices available in vmware

### ISSUE THREAD

**Issue by catsigma** [maierfelix/nvk#44]
The operating system is ubuntu 18.04. And it can run `glxgears` without a problem.

When I'm trying to run the `nvk-examples/triangle` the following info shows up:

```
> node --inspect --experimental-modules ./index.mjs

Debugger listening on ws://127.0.0.1:9229/79ced56b-8ae6-4e39-aab5-cddfb11a6974
For help, see: https://nodejs.org/en/docs/inspector
(node:3214) ExperimentalWarning: The ESM module loader is experimental.
(nvk) Using Vulkan v1.1.114
(nvk) Validation checks are enabled
Error: No render devices available!
Error: Vulkan assertion failed!
    at ASSERT_VK_RESULT (file:///home/dev/Codes/temp/nvk-examples/triangle/index.mjs:27:36)
    at file:///home/dev/Codes/temp/nvk-examples/triangle/index.mjs:172:1
    at ModuleJob.run (internal/modules/esm/module_job.js:95:12)
```
Here is the info when running `glmark2`:
```
=======================================================
    glmark2 2014.03+git20150611.fa71af2d
=======================================================
    OpenGL Information
    GL_VENDOR:     VMware, Inc.
    GL_RENDERER:   SVGA3D; build: RELEASE;  LLVM;
    GL_VERSION:    3.0 Mesa 18.0.5
=======================================================

```

Don't know if there is a way to run vulkan in Vmware.

**Comment by maierfelix** [comment]
I've never tried running this project in a VMware. The error means, that Vulkan didn't return any compatible GPU at all. Are you able to run other Vulkan applications, the demos in the Vulkan SDK for example?

**Comment by catsigma** [comment]
Yeah, you're right.
